openapi: 3.0.0
info:
  title: Point Ledger
  version: 1.0.0
components:
  schemas:
    PointLedger:
      type: object
      required: [userId, balance]
      properties:
        userId:
          type: string
        balance:
          type: integer
