openapi: 3.0.0
info:
  title: Create Payment
  version: 1.0.0
paths:
  /payments:
    post:
      summary: Create payment intent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required: [userId, amount]
              properties:
                userId:
                  type: string
                amount:
                  type: number
      responses:
        '200':
          description: Payment created