openapi: 3.0.0
info:
  title: Error Response
  version: 1.0.0
components:
  schemas:
    Error:
      type: object
      required: [code, message]
      properties:
        code:
          type: string
        message:
          type: string